trigger:
- master
- develop

pr:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

# because this project has Tests in the name we cant publish indiviual frameworks at this time.
variables:
  support_netstandard20: false
  support_netstandard21: false
  support_netcoreapp21: false
  support_netcoreapp31: false
  support_net5_0: false
  Major: 0
  Minor: 9

resources:
  repositories:
    - repository: templates
      type: github
      name: Sannel/Sannel.House.BuildScripts
      endpoint: Sannel

jobs:
- template: tasks/library.yml@templates  # Template reference